-- make sure plugins installed before configuring
require('plugins.colorschemes')
require('plugins.fugative')
require('plugins.oil')
require('plugins.telescope')
require('plugins.mason')
require('plugins.vim-tmux-navigator')
require('plugins.treesitter')
require('plugins.dap')
require('plugins.autocomplete')
require('plugins.harpoon')

require('config.globals')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')
require('config.colorscheme')
